name: CI

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Build the Docker image
        run: docker build -t zhyannick/m346-ref-card-02 .
      - name: Login to Docker Hub
        run: docker login -u zhyannick -p  ${{ secrets.DOCKER_PASSWORD }}
      - name: Push the Docker image
        run: docker push zhyannick/m346-ref-card-02
